#!/usr/bin/env node

const yargs = require('yargs');
const inquirer = require('inquirer');
const chalk = require('chalk');
const main = require('./modules/main');

const argv = yargs
    .options({
        'fileName': {
            alias: 'f',
            describe: 'Your new custom name',
            demandOption: false
        },
        'type': {
            alias: 't',
            describe: 'Type of files you want to rename',
            demandOption: false
        },
        'typeGroup': {
            alias: 'g',
            describe: "Rename files only of a certain kind: images | docs | video | audio | dev"
        },
        'imageSizeGroup': {
            alias: 'i',
            describe: 'Adds image size group with suffix or prefix '
        },
        'suffix': {
            alias: 's',
            describe: 'Adds custom suffix to the existing file name',
            demandOption: false
        },
        'prefix': {
            alias: 'p',
            describe: 'Adds custom prefix to the existing file name',
            demandOption: false
        }
    })
    .help()
    .argv;

inquirer
    .prompt([{
        type: 'confirm',
        name: 'areYouShure',
        message: chalk.yellow(`Current file names ${chalk.red.underline.bold('will be lost')}. Are you sure? `),
        default: false
    }])
    .then(({
        areYouShure
    }) => {
        areYouShure && main.runRename(argv);
    });
